### ISSUE TITLE
Home page, down under 'Programs', update GROUP to the following text in comments section

### ISSUE THREAD

**Issue by kendra-chasing-english** [chefThomas/chasing-english#110]
Achievement is often bolstered in cooperative learning environments. These courses offer an assortment of learning opportunities that cover everything from sharing insight into literature; developing grammar and writing skills; and preparing for both high school and college admissions. Learning is enriched by extended viewership, peer-editing and discourse, and social interaction.

**Comment by chefThomas** [comment]
Request approval of this minor edit to the passage. 

Achievement is often bolstered in cooperative learning environments. These courses offer an assortment of learning opportunities covering everything from sharing insight into literature, developing grammar and writing skills, to high school and college admission preparation. Learning is enriched by extended viewership, peer-editing, and discourse.
