### ISSUE TITLE
Homepage: Mission Statement --Photographs

### ISSUE THREAD

**Issue by kendra-chasing-english** [chefThomas/chasing-english#23]
![image](https://user-images.githubusercontent.com/61162346/74681069-4a6f7d00-5177-11ea-84c6-4ed49eb9aabd.png)

![image](https://user-images.githubusercontent.com/61162346/74681119-6d9a2c80-5177-11ea-982d-ace6258bd82c.png)

**Comment by chefThomas** [comment]
there's only room for one picture in current layout. using both would require a lot of styling changes. used writing picture after approval
