### ISSUE TITLE
Homepage: 'Course Type Description' Individual Coaching Photograph

### ISSUE THREAD

**Issue by kendra-chasing-english** [chefThomas/chasing-english#27]
![image](https://user-images.githubusercontent.com/61162346/74681823-3e84ba80-5179-11ea-9cf5-f89907779739.png)

**Comment by chefThomas** [comment]
request for image as background with text block overlay, as seen [here](https://www.w3schools.com/howto/howto_css_image_text_blocks.asp)

**Comment by chefThomas** [comment]
picture resolution too low. consult for change

**Comment by chefThomas** [comment]
switched to illustrations
